### ISSUE TITLE
No printing in daemon mode

### ISSUE THREAD

**Issue by jgantenberg** [armooo/cloudprint#101] opened 2015-06-17 10:10 UTC
Cloudprinting in general works with my setup. When I start cloudprint with the following command line all requests are directed to cups and are being printed:
/usr/local/bin/cloudprint -v -a /var/lib/cloudprint/authfile -p /var/run/cloudprint.pid
But when I insert a "-d" option for daemon mode, the cloudprinters come online again, but no print requests are directed to cups. In GCP job status page all jobs are marked "printed". 
In syslog I only see 
Jun 17 11:57:54 localhost cloudprint.py: Setting DEBUG-level logging
Jun 17 11:57:56 localhost cloudprint.py: Updated Printer PDF
Jun 17 11:57:57 localhost cloudprint.py: Updated Printer Kyocera_Mita_FS-1020D
and nothing more from cloudprint. If started not in daemon mode I see logs on the command line for every print request

Did I miss something?

**Comment by rasmussolmer** [comment] 2015-06-23 15:02
Same problem here - none of the usual "Polling for jobs on..." in the syslog when running the script in daemon mode. Problem seems to have occurred during the shift to OAuth2

**Comment by davesteele** [comment] 2015-06-24 15:24
This doesn't appear to be the culprit, but FYI:

Date: Fri, 5 Jun 2015 11:42:41 +1000
From: Ben Finney <ben+debian@benfinney.id.au>

Howdy,

 You are maintaining a package with a dependency on ‘python-daemon’. In
 turn, this brings a dependency on ‘python-lockfile’.

 Debian's package ‘python-lockfile’ has recently updated to one with a
 backward-incompatible API. (In summary: exported names in the API have
 changed, and dependent code must change accordingly. See its changelog
 for more detail.)

 The ‘python-daemon’ code has changed in many ways since the version
 1.5.x series. The 2.x series now depends on the current
‘python-lockfile’ API, and it is that version of ‘python-daemon’ which
 will be soon uploaded to Debian.

 Please check the package you maintain to see whether it is compatible
 with upstream ‘python-daemon’ version 2 or later.

 If the package is compatible only with earlier ‘python-daemon’
versions, I recommend declaring this in the package metadata. A field
“Depends: python-daemon (<= 1.6)” would be good.

 If there is an upstream version of your package that is compatible
 *only* with ‘python-daemon’ version 2 or later, please package that
 version with “Depends: python-daemon (>= 2)”.

 The backward-incompatible ‘python-daemon’ will likely be uploaded into
 Debian within a few weeks.

 Please let me wknow if you need assistance with this issue.

**Comment by armooo** [comment] 2015-06-24 15:42
I think this may be the cause it looks like the new python-daemon fails silently. I was able to get it to work by pip installing an older version of python-daemon and lockfile.

**Comment by chrbkr** [comment] 2015-06-25 16:21
For me, the printers do NOT come online in daemon mode.

**Comment by matthiasdg** [comment] 2015-06-25 18:58
I also just changed to an OAuth2 version, and am also having this problem.
My python-daemon and lockfile are quite old (tried 1.5.2 and 0.8), but the problem persists.
The daemon keeps running (ps lists the process) but the printer is NOT online in google's cloud print web interface. Working fine without -d

**Comment by armooo** [comment] 2015-07-09 03:18
This was fixed in 88acead3. If you installed with pip `pip install --upgrade cloudprint[daemon]` will update all the required dependencies.

**Closed by armooo** 2015-07-09 03:18 UTC

**Comment by rasmussolmer** [comment] 2015-07-10 09:16
Thank you for working on this issue.

I have updated everything with the pip command as specified, but my print job fails according to the google cloudprint dashboard.

The daemon job seems to be running ok, but I see no errors in the syslog.
pi@raspberry ~ $ ps aux |grep cloud
pi        4171  1.9  4.9  27244 21964 ?        S    11:10   0:06 /usr/bin/python /usr/local/bin/cloudprint -d

**Comment by matthiasdg** [comment] 2015-07-10 09:39
Guess this is the same problem I had with an old version of python-daemon (before this fix). So maybe the underlying cause is something else?
(For now I ended up using daemontools' supervise with cloudprint, which is working fine)

**Comment by davesteele** [comment] 2015-07-10 18:12
My 0.12 install fails with the hourly REST call (https://github.com/davesteele/cloudprint-service/issues/34). Perhaps there is an OAuth issue?

**Comment by davesteele** [comment] 2015-07-12 00:38
fixed in 0.13
